apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: development-pvc
  namespace: kube-system
spec:
  accessModes:
    - ReadWriteOnce
  # storageClassName: ebs-storageclass // when multi storageclass exist,you can sepcify
  resources:
    requests:
      storage: 5Gi
