apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: development-box
  namespace: kube-system
spec:
  serviceName: "development-box"
  replicas: 2
  selector:
    matchLabels:
      app: development-box
  template:
    metadata:
      labels:
        app: development-box
    spec:
      containers:
      - name: development-box
        image: uhub.service.ucloud.cn/entropypool/development-box:latest
        imagePullPolicy: Always
        env:
        - name: ENV_ENVIRONMENT_TARGET
          valueFrom:
            configMapKeyRef:
              name: system-environment
              key: environment.target
        - name: ENV_CONSUL_HOST
          valueFrom:
            configMapKeyRef:
              name: system-environment
              key: environment.consul_host
        - name: ENV_CONSUL_PORT
          valueFrom:
            configMapKeyRef:
              name: system-environment
              key: environment.consul_port
        - name: PATH
          value: "/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/sbin:/bin"
        - name: GOPROXY
          value: "https://goproxy.cn,direct"
        command: ["sleep", "100000000000000"]
        volumeMounts:
        - name: work
          mountPath: /workspace
      volumes:
      - name: work
        persistentVolumeClaim:
          claimName: development-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: development-box
  namespace: kube-system
spec:
  type: NodePort
  ports:
  - port: 22
    targetPort: 22
    nodePort: 30022
    name: ssh
    protocol: TCP
  selector:
    app: development-box
