apiVersion: apps/v1
kind: Deployment
metadata:
  name: development-box
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: development-box
  template:
    metadata:
      labels:
        app: development-box
    spec:
      containers:
      - name: development-box
        image: entropypool/development-box:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: ENV_ENVIRONMENT_TARGET
          valueFrom:
            configMapKeyRef:
              name: system-environment
              key: environment.target
        - name: ENV_CONSUL_HOST
          valueFrom:
            configMapKeyRef:
              name: system-environment
              key: environment.consul_host
        - name: ENV_CONSUL_PORT
          valueFrom:
            configMapKeyRef:
              name: system-environment
              key: environment.consul_port
        - name: PATH
          value: "/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/sbin:/bin"
        - name: GOPROXY
          value: "https://goproxy.cn,direct"
        command: ["sleep", "100000000000000"]
        
